# Generated by Django 5.1.3 on 2025-01-10 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_tbl_package_type_tbl_location_tbl_location_gallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_package_type',
        ),
    ]
