# Generated by Django 5.1.3 on 2025-01-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_delete_tbl_package_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_package_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type_name', models.CharField(max_length=50)),
            ],
        ),
    ]
