# Generated by Django 5.1.3 on 2025-01-17 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0008_tbl_package_type'),
        ('Guest', '0011_tbl_travelagency'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=100)),
                ('package_price', models.CharField(max_length=100)),
                ('package_details', models.CharField(max_length=1000)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_travelagency')),
                ('package_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_package_type')),
            ],
        ),
    ]
