# Generated by Django 5.1.3 on 2025-01-21 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_tbl_package_type'),
        ('TravelAgency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_packagelocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_location')),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TravelAgency.tbl_package')),
            ],
        ),
    ]
