# Generated by Django 5.1.3 on 2025-01-06 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_tbl_subcategory'),
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_registration',
            name='photo',
            field=models.FileField(upload_to='Assets/Files/User'),
        ),
        migrations.AlterField(
            model_name='tbl_registration',
            name='proof',
            field=models.FileField(upload_to='Assets/Files/User'),
        ),
        migrations.CreateModel(
            name='tbl_travelagency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=50)),
                ('agency_email', models.CharField(max_length=50)),
                ('agency_contact', models.CharField(max_length=50)),
                ('agency_Address', models.CharField(max_length=50)),
                ('agency_photo', models.FileField(upload_to='Assets/Files/User')),
                ('agency_license', models.FileField(upload_to='Assets/Files/User')),
                ('agency_password', models.CharField(max_length=50)),
                ('agency_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
