# Generated by Django 5.1.3 on 2025-01-09 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0005_tbl_subcategory'),
        ('Guest', '0003_remove_tbl_travelagency_agency_place_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_travelagency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=50)),
                ('agency_email', models.CharField(max_length=50)),
                ('agency_contact', models.CharField(max_length=50)),
                ('agency_address', models.CharField(max_length=50)),
                ('agency_photo', models.FileField(upload_to='Assets/Files/User')),
                ('agency_license', models.FileField(upload_to='Assets/Files/User')),
                ('agency_password', models.CharField(max_length=50)),
                ('agency_status', models.CharField(max_length=50)),
                ('agency_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=50)),
                ('user_contact', models.CharField(max_length=50)),
                ('user_address', models.CharField(max_length=100)),
                ('user_photo', models.FileField(upload_to='Assets/Files/User')),
                ('user_proof', models.FileField(upload_to='Assets/Files/User')),
                ('user_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
