# Generated by Django 5.1.3 on 2025-01-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0008_tbl_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_travelagency',
            name='agency_status',
            field=models.IntegerField(default=0),
        ),
    ]
