# Generated by Django 5.1.3 on 2025-01-17 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0009_alter_tbl_travelagency_agency_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_travelagency',
        ),
    ]
