# Generated by Django 5.1.3 on 2025-01-21 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0011_tbl_travelagency'),
        ('TravelAgency', '0002_tbl_packagelocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_date', models.DateField(auto_now=True)),
                ('complaint_content', models.CharField(max_length=500)),
                ('complaint_status', models.IntegerField(default=0)),
                ('complaint_reply', models.CharField(max_length=500)),
                ('agency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_travelagency')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_content', models.CharField(max_length=500)),
                ('feedback_date', models.DateField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_packagebooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packagebooking_status', models.IntegerField(default=0)),
                ('packagebooking_date', models.DateField(auto_now=True)),
                ('packagebooking_fordate', models.DateField()),
                ('person_count', models.IntegerField(default=0)),
                ('packagelocation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TravelAgency.tbl_packagelocation')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_content', models.CharField(max_length=500)),
                ('rating_value', models.IntegerField(default=0)),
                ('rating_datetime', models.DateTimeField(auto_now=True)),
                ('agency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_travelagency')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
