# Generated by Django 5.1.3 on 2025-01-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_packagebooking',
            name='person_count',
            field=models.CharField(max_length=100),
        ),
    ]
