# Generated by Django 5.1.3 on 2025-01-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_tbl_packagebooking_person_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_packagebooking',
            name='person_count',
            field=models.IntegerField(default=0),
        ),
    ]
