# Generated by Django 5.1.3 on 2025-02-07 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_tbl_package_type'),
        ('Guest', '0011_tbl_travelagency'),
        ('User', '0003_alter_tbl_packagebooking_person_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_locationreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_date', models.DateField(auto_now_add=True)),
                ('location_review', models.CharField(max_length=500)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
